import { createI18n } from "vue-i18n";

export const lang = {
  ru: {
    login: {
      titleLogIn: "Вход",
      titleRegist: "Регистрация",
      usernamePlaceholder: "никнейм",
      passwordPlaceholder: "пароль",
      passwordRepeatPlaceholder: "повторите пароль",
      emailPlaceholder: "почта",
      submitButton: "войти",
      regisButton: "зарегистрироваться",
      hintRegist: "Нет аккаунта?",
      hintLogIn: "Уже есть аккаунт?",
      linkRegist: "Зарегистрироваться.",
      linkLogIn: "Войти.",

      errorNoData: "пожалуйста, заполните поля",
      errorPasswordMatch: "пароли не совпадают",
      errorPasswordValid: "пароль дожен быть минимум из 6 символов",
      errorUsernameTaken: "этот никнейм занят",
      errorUsernameValid: "никнейм должен быть минимум из 2 символов",
      errorNoSuchAcc: "пользователь не найден или неверный пароль",
    },
    sideBar: {
      searchInput: "искать задачу",
      categTitle: "Категории",
      categWork: "работа",
      categStudy: "учеба",
      categPersonal: "личное",
      addCategButton: "добавить категорию +",
      categoryName: "название категории",
      settings: "настройки",
    },
    taskManager: {
      greeting: "Привет, ",
      addTaskInput: "новая задача",
      addTaskButton: "добaвить +",
      filterToday: "сегодня",
      filterAll: "все",
      filterActive: "активно",
      filterDone: "сделано",
      tasks: "задач",
      titleAllTasks: "Все задачи",
      titleActiveTasks: "Активные задачи",
      titleDoneTasks: "Сделанные задачи",
      titleTodayTasks: "На сегодня",
      noTasksMessage: "Задачи не найдены",
      deleteAllDoneTasksButton: "удалить готовые задачи",
    },
    settings: {
      title: "Настройки",
      titleAccount: "Аккаунт",
      titleTodoSet: "Настройки приложения",
      titleTheme: "Тема",
      themeLight: "Светлая",
      themeDark: "Темная",
      logOutButton: "выйти",
      editButton: "изменить",
    },
  },
  en: {
    login: {
      titleLogIn: "Log in",
      titleRegist: "Register",
      usernamePlaceholder: "username",
      passwordPlaceholder: "password",
      passwordRepeatPlaceholder: "repeat password",
      emailPlaceholder: "email",
      submitButton: "log in",
      regisButton: "registrate",
      hintRegist: "Do not have an account?",
      hintLogIn: "Already have an account?",
      linkRegist: "Register.",
      linkLogIn: "Log in.",

      errorNoData: "please, write your data",
      errorPasswordMatch: "passwords do not match",
      errorPasswordValid: "password must be at least 6 symbols",
      errorUsernameTaken: "this username is taken",
      errorUsernameValid: "usersname must be at least 2 symbols",
      errorNoSuchAcc: "no such account or wrong password",
    },
    sideBar: {
      searchInput: "search task by name",
      categTitle: "Categories",
      categWork: "work",
      categStudy: "study",
      categPersonal: "personal",
      addCategButton: "add category +",
      categoryName: "category name",
      settings: "settings",
    },
    taskManager: {
      greeting: "Hello, ",
      addTaskInput: "new task title",
      addTaskButton: "add +",
      filterToday: "today",
      filterAll: "all",
      filterActive: "active",
      filterDone: "done",
      tasks: "tasks",
      titleAllTasks: "All tasks",
      titleActiveTasks: "Active tasks",
      titleDoneTasks: "Done tasks",
      titleTodayTasks: "Today tasks",
      noTasksMessage: "No tasks found",
      deleteAllDoneTasksButton: "delete done tasks",
    },
    settings: {
      title: "Settings",
      titleAccount: "Account",
      titleTodoSet: "Todo settings",
      titleTheme: "Theme",
      themeLight: "Light",
      themeDark: "Dark",
      logOutButton: "log out",
      editButton: "edit",
    },
  },
};

export const i18n = createI18n({
  legacy: false,
  locale: "en",
  fallbackLocale: "en",
  messages: lang,
});
